name: paws_care
description: "Paws & Care - Platform pelaporan dan bantuan hewan jalanan"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  google_maps_flutter: ^2.3.0
  geolocator: ^14.0.2
  image_picker: ^1.0.7
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48

flutter:
  uses-material-design: true
  assets:
  - assets/icon/   

