name: paws_care
description: "Paws & Care - Platform pelaporan dan bantuan hewan jalanan"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  image_picker: ^1.0.7
  intl: ^0.18.0
  geolocator: ^11.0.0
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.2.1
  google_maps_flutter: ^2.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
