// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSLit2hno644A-S2GoHUMqARTkH1lpfCw',
    appId: '1:189274994253:web:080777d0cb3bc8b94a4e04',
    messagingSenderId: '189274994253',
    projectId: 'pawscare-3b14d',
    authDomain: 'pawscare-3b14d.firebaseapp.com',
    databaseURL: 'https://pawscare-3b14d-default-rtdb.firebaseio.com',
    storageBucket: 'pawscare-3b14d.firebasestorage.app',
    measurementId: 'G-1MH02HJG30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhATgJWdIubisZttOY4NkN9mSyrltoUnk',
    appId: '1:189274994253:android:31d3c0fd3098bf914a4e04',
    messagingSenderId: '189274994253',
    projectId: 'pawscare-3b14d',
    databaseURL: 'https://pawscare-3b14d-default-rtdb.firebaseio.com',
    storageBucket: 'pawscare-3b14d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEPapw5ehWtrSLwjElL9q1pY8Uz2L4FYs',
    appId: '1:189274994253:ios:7e6ea74c7f4473034a4e04',
    messagingSenderId: '189274994253',
    projectId: 'pawscare-3b14d',
    databaseURL: 'https://pawscare-3b14d-default-rtdb.firebaseio.com',
    storageBucket: 'pawscare-3b14d.firebasestorage.app',
    iosBundleId: 'com.example.pawsCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEPapw5ehWtrSLwjElL9q1pY8Uz2L4FYs',
    appId: '1:189274994253:ios:7e6ea74c7f4473034a4e04',
    messagingSenderId: '189274994253',
    projectId: 'pawscare-3b14d',
    databaseURL: 'https://pawscare-3b14d-default-rtdb.firebaseio.com',
    storageBucket: 'pawscare-3b14d.firebasestorage.app',
    iosBundleId: 'com.example.pawsCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSLit2hno644A-S2GoHUMqARTkH1lpfCw',
    appId: '1:189274994253:web:1d0a8064129b56454a4e04',
    messagingSenderId: '189274994253',
    projectId: 'pawscare-3b14d',
    authDomain: 'pawscare-3b14d.firebaseapp.com',
    databaseURL: 'https://pawscare-3b14d-default-rtdb.firebaseio.com',
    storageBucket: 'pawscare-3b14d.firebasestorage.app',
    measurementId: 'G-PYVHBCJW8W',
  );
}
